stage2_ver.1
AleksandrDronov/react-burger pull request #2
Opened 2022-07-06 18:55 UTC by AleksandrDronov

2022-07-07 01:46 UTC, kyzinatra commented on src/components/header/header.jsx
> +            <span className="text text_type_main-default pl-2 pr-2">Конструктор</span>
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например

`<a href="#" class="......">`

…
 `Конструктор` 

….
`</a>`

В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

2022-07-07 01:48 UTC, kyzinatra commented on src/components/app/app.jsx
> +    const getData = async () => {
Можно лучше: испортируйте `useEffect` сразу при импорте
`import React, {useEffect} from 'react';`
и тогда можно просто 

```js

useEffect(() => {...}, [...])
```

2022-07-07 01:50 UTC, kyzinatra commented on src/components/app/app.jsx
> +      if(res.ok) {
Надо исправить: помимо проверки `res.ok` также нужно проверить и просто ошибку запроса с помощью `try{} cacth(e){}` или `.catch()` после fetch, как синтаксис промисов

2022-07-07 01:51 UTC, kyzinatra commented on src/components/app/app.jsx
> +        { data.length && success && <BurgerConstructor data={data} />}
Можно лучше: лучше 2 раза не повторять условие, а использовать `<> ... </>`, чтобы обьеденить все в 1

2022-07-07 01:52 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
> +          ))}
Можно лучше: мне кажется что заголовок и рендер каждой категории стоит вынести в отдельный компонент. В будущем тут будет очень много функционала, так что будет проще

2022-07-07 01:53 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
> +};
Отлично! Хорошая типизация

2022-07-07 01:54 UTC, kyzinatra commented on src/components/burger-сonstructor/burger-сonstructor.jsx
> +          thumbnail={data[0].image}
Можно лучше: В общем случае мне кажется, что булку лучше брать, не как `[0]` элемент, а как результат вызова `.find()`, где бы искали `type === "bun"`

2022-07-07 01:56 UTC, kyzinatra commented on src/components/burger-сonstructor/burger-сonstructor.jsx
> +            <DragIcon type="primary"/>
Можно лучше: лучше не использовать тут ключ `item._id` так как в будущем в конструкторе может быть несколько компонентов одного и того же типа. В будущем вы исправите это иначе, а пока лучше поставить  `index` массива как ключ

2022-07-07 01:59 UTC, kyzinatra commented on src/components/burger-сonstructor/burger-сonstructor.jsx
> +  });
Надо исправить: не стоит использовать названия вроде state, value, data, array. Так как это клише и почти ничего не говорит о том, что внутри. Конкретно в данном случае я бы использовал что-то вроде `isModalOpen`/`isModalVisible` и `setModalOpen`/`setModalVisible`. Тогда как значение стейт можно оставить просто булево значение

2022-07-07 01:59 UTC, kyzinatra commented on src/components/app/app.jsx
> +    success: false,
Надо исправить: по аналогии сменить имя переменной

2022-07-07 02:00 UTC, kyzinatra commented on src/components/card/card.jsx
> +  });
Надо исправить: по аналогии сменить имя переменной

2022-07-07 02:02 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- Убрать все имена state и им подобные
- обернуть иконку и текст в шапке в ссылку
- проверять ошибку в самом запросе

Можно лучше:

- Использовать `<> </>`, вместо 2 одинаковых условий
- заголовок и рендер каждоый категории стоит вынести в отдельный компонент. В булдщем тут будет очень много функционала, так что будет проще

Что понравилось:

- Хорошо реализованы модальные Выглядит очень круто! Видно, что проделана большая работа.


Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2022-07-07 11:36 UTC, AleksandrDronov commented on src/components/burger-ingredients/burger-ingredients.jsx
> +          ))}
спасибо. учту на следующем этапе

2022-07-07 11:59 UTC, AleksandrDronov commented on src/components/burger-сonstructor/burger-сonstructor.jsx
> +            <DragIcon type="primary"/>
спасибо. На прошлой итерации проверки ревьювер сказал что лучше не использовать индекс массива).

2022-07-07 12:19 UTC, AleksandrDronov commented
Спасибо за проверку. Комментарии учтены и исправлены.

2022-07-08 04:00 UTC, kyzinatra commented on src/components/burger-сonstructor/burger-сonstructor.jsx
> +            <DragIcon type="primary"/>
Я глянул прошлое ваше ревью. Там Генадий говорил о компоненте burger-ingredients. Там все компоненты уникальны так что не будет проблем с тем, чтобы использовать  `item._id`, наоборот, там это оптимальный способ, но тут в `burger-constructor` тут может быть такое, что у вас идет к примеру 2 одинаковых соуса с один и тем же _id, тогда при генерации ключи будут совпадать и будет ошибка в консоли, что еще хуже чем просто не указывать ключ)
В будущем, когда пользователь будет добавлять из списка ингредиент в конструктор вы будете сами генерировать для каждого ингредиента уникальный id и использовать уже его в качестве ключа. Именно поэтому пока что я вас попросил именно тут оставить индекс, а в burger-ingredients все отлично. Там нужен именно  `item._id`

2022-07-08 04:05 UTC, kyzinatra commented
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

**По поводу ключей, ответил вам в диалоге выше. Надесь стало понятнее почему именно так**

2022-07-30 14:07 UTC, merged